package io.redgreen.timelapse.devcli.commands.xd.html

import org.approvaltests.core.Options
import org.approvaltests.scrubbers.RegExScrubber

private val toolVersionScrubber = RegExScrubber(
  "<!--Generated by dev-cli: v\\d+.\\d+.\\d+(-\\w+)?-->",
  "<!--Generated by dev-cli: v[tool-version]-->"
)
internal val scrubberOptions = Options(toolVersionScrubber)
